code-quality:
    - source-code-quality-clang-tidy
    - source-code-quality-cppcheck
    - test-code-quality-clang-tidy
    - test-code-quality-cppcheck
    - code-quality-clang-format
    - code-quality-black-format

compile:
    - compile-psoc6-cy8ckit_062s2_ai
